### ISSUE TITLE
App crashes when <modal> component is removed from PostDetail

### ISSUE THREAD

**Issue by jacobtyq** [jobsgowhere/jobsgowhere#150]
App crashes when `<modal></modal>` in `PostDetail.tsx` is removed. 

See comment:
https://github.com/jobsgowhere/jobsgowhere/pull/145#issuecomment-702111863

**Comment by SheldonCheng** [comment]
You are using custom hooks that are initialised from inside `Modal` component, so `Modal` needs to be mounted for the hooks to work.

Also the proper syntax for component without children is `<Modal />`, so it doesn't look like a mistake.

Anyway I have refactored the implementation here:
https://github.com/jobsgowhere/jobsgowhere/pull/155

**Comment by jacobtyq** [comment]
Noted on the syntax bit.

I understand that the hooks are initialized from inside `Modal` component, so without mounting it, it would cause the app to crash as there is no function to call. 

What I don't really get is how the `useMessageDialog` component does not require initialization as well. What is the `useMessageDialog` component that is doing differently that does not require it to be mounted?

**Comment by SheldonCheng** [comment]
Ah but actually `useMessageDialog` component is already initialised: it is imported and used in `Layout.tsx`.

Truthfully, `useToast` and `useMessageDialog` are not great examples of typical portal usage. So if you were referencing them, my bad, hope you didn't learn the wrong thing 😞 

Both can actually work without using portals: putting `ToastContainer` and `MessageDialogContainer` in Layout basically circumvents the purpose of portals. Also, their approach is designed to export one (or two) simple utility-like functions: eg `toast("hi") `.

For general purpose components like modals, you tend to want it to be used as a component rather than a function, as I've refactored it in #155 . This case is also where portals become useful (use modal anywhere, but it always mounts as a direct child of `body` in DOM).
For a good example of modals (and a11y), check out Reach UI's [Dialog component](https://reach.tech/dialog/).

**Comment by SheldonCheng** [comment]
Fixed by #155
