### ISSUE TITLE
Backend - Talent API Structure

### ISSUE THREAD

**Issue by subhransu** [jobsgowhere/jobsgowhere#88]
Change the structure of API.

**Comment by subhransu** [comment]
Closing this as this done in #89

**Comment by SheldonCheng** [comment]
@subhransu @kajalsinha While working on Talents pagination, I noticed that the `itemsPerPage` value in `talent/controller.go` is not being respected.

I dug abit and I think the issue is with the `GetTalents` method in `talents/repository.go`. Seems to be missing the `Offset` and `Limit` calls that is present in the jobs version file

**Comment by subhransu** [comment]
Created issue #98 for this.
